### ISSUE TITLE
OSX/Mavericks: Streams crackling after short period of time

### ISSUE THREAD

**Issue by herrnst** [kxproject/kx-audio-driver#5]
(prequel: I apologize if this is the wrong area to post issues regarding the (OSX)driver)

Hello,

am using the OSX driver to run a SB0350 (Audigy 2 ZS, emu10k2) on Mavericks (10.9.2) on a Sandybridge hack. The driver causes a quite annoying issue (which definitely isn't there on Win and Linux, and wasn't there at least on OSX Lion):

Whenever audio is played back, after a random but usually short amount of time (from one minute up to ten minutes, seems it can be amplified by putting load on the system) the audio stream starts crackling, sounding as if some kind of buffer would be either shifted or overrun, but the original sound is still noticeable (so it doesn't just start to make random noise). Stopping and starting the stream again (e.g. in iTunes, hit stop and start) fixes it temporarily until it starts to make buffer-shifting sounds again. Only stereo speakers are connected, Audio/MIDI setup is configured for stereo mode aswell. Aside from this, audio playback works very well and stable.

Honestly I don't know anything about all things kernel, driver and/or CoreAudio related on OSX, but I'm able (and willing!) to build the driver from the sources and can of course test things.

Again, I apologize if this is the wrong place to post issues.

**Comment by owenjbrady** [comment]
I still use this card its way louder then my realtek on board

**Comment by owenjbrady** [comment]
@herrnst how do I apply this patch? do I just add it into the list do I have to somehow recompile it? I am a windows/linux user new to mac would really like to get this card stable in OS X 10.10 but I am a noob with these mac drivers.... is there anyway you can just zip me yours? much appreciated.

**Comment by wujekbogdan** [comment]
I have already done it. Here you can download compiled kext: http://hamac.pl/topic/10045-audigy-2-poprawiony-sterownik-kx/
btw, compiling can't be easier. there's a .xcodeproj directory committed to the repository, so all you have to do is to import the project to xcode and find compilation options in the menus :)

**Comment by owenjbrady** [comment]
@wujekbogdan thank you so much really mean that!

**Comment by wujekbogdan** [comment]
No. All you need is the `.kext` file.
