### ISSUE TITLE
Do you have plan to port this to android?

### ISSUE THREAD

**Issue by qdk0901** [kxproject/kx-audio-driver#9]

**Comment by seven-phases-max** [comment]
kX works with the specific hardware. I don't think you have (or will ever have) such hardware in/with Android devices.

**Comment by qdk0901** [comment]
we want to mount a kX compatible sound card or chip to our OTT-Box board which runs Android
I see most kX compatible sound cards are using PCI or PCI-E interface,  the SOC on the OTT-Box board support PCI and PCI-E interface, so I think hardware is not a problem(correct me if I'm wrong)

**Comment by schmatzler** [comment]
Android works on top of a Linux kernel and supports ALSA, so you can already use emu10k* chipsets on it with the ALSA driver. No need for this driver there, at least for simple audio output.

**Comment by seven-phases-max** [comment]
@qdk0901 
>a kX compatible sound card or chip to our OTT-Box 

I see. Nice (sorry for my ignorance then, I did not hear of such devices before).

---
Either way, kX is developed in 2001-2002 (with most of planned features and facilities finished and polished by 2003). So I'd barely expect anyone of the initial contributors to be really interested to take any major efforts in further development by now. So if there're any ideas of further development/ports it's totally up to one having such idea.
